package net.bittreasury.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2018-6-13 22:16:01 by Hibernate Tools 5.2.8.Final

/**
 * Manager generated by hbm2java
 */
@Entity(name = "oo_manager")
public class Manager implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer mid;
	@Column
	private String mname;
	@Column
	private String mpassword;

	public Manager() {
	}

	public Manager(Integer mid) {
		this.mid = mid;
	}

	public Manager(Integer mid, String mname, String mpassword) {
		this.mid = mid;
		this.mname = mname;
		this.mpassword = mpassword;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMpassword() {
		return this.mpassword;
	}

	public void setMpassword(String mpassword) {
		this.mpassword = mpassword;
	}

}
