package net.bittreasury.entity;
// Generated 2018-6-13 22:16:01 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Team generated by hbm2java
 */
@Entity(name = "oo_team")
public class Team implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer teamId;
	@Column
	private String teamName;
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "team_a")
	private Set<Match> matchsTeamA = new HashSet<>();
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "team_b")
	private Set<Match> matchsTeamB = new HashSet<>();
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "winner")
	private Set<Match> matchsWinner = new HashSet<>();
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "team")
	private Set<User> users = new HashSet<>();

	
	/**
	 * @return the teamId
	 */
	public Integer getTeamId() {
		return teamId;
	}

	/**
	 * @param teamId
	 *            the teamId to set
	 */
	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	/**
	 * @return the teamName
	 */
	public String getTeamName() {
		return teamName;
	}

	/**
	 * @param teamName
	 *            the teamName to set
	 */
	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	/**
	 * @return the matchsTeamA
	 */
	public Set<Match> getMatchsTeamA() {
		return matchsTeamA;
	}

	/**
	 * @param matchsTeamA the matchsTeamA to set
	 */
	public void setMatchsTeamA(Set<Match> matchsTeamA) {
		this.matchsTeamA = matchsTeamA;
	}

	/**
	 * @return the matchsTeamB
	 */
	public Set<Match> getMatchsTeamB() {
		return matchsTeamB;
	}

	/**
	 * @param matchsTeamB the matchsTeamB to set
	 */
	public void setMatchsTeamB(Set<Match> matchsTeamB) {
		this.matchsTeamB = matchsTeamB;
	}

	/**
	 * @return the matchsWinner
	 */
	public Set<Match> getMatchsWinner() {
		return matchsWinner;
	}

	/**
	 * @param matchsWinner the matchsWinner to set
	 */
	public void setMatchsWinner(Set<Match> matchsWinner) {
		this.matchsWinner = matchsWinner;
	}

	/**
	 * @return the users
	 */
	public Set<User> getUsers() {
		return users;
	}

	/**
	 * @param users the users to set
	 */
	public void setUsers(Set<User> users) {
		this.users = users;
	}




	

}
