package net.bittreasury.entity;
// Generated 2018-6-13 22:16:01 by Hibernate Tools 5.2.8.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * User generated by hbm2java
 */
@Entity(name = "oo_user")
public class User implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column
	private Integer uid;
	// @Column
	// private Integer team;

	@ManyToOne(cascade = { CascadeType.REFRESH, CascadeType.MERGE }, optional = true)
//	@JoinColumn(name = "team_id", unique = true)
	private Team team;

	@Column
	private String uname;
	@Column
	private String upassword;
	@Column
	private String isfootballer;

	public User() {
	}

	public User(Integer uid) {
		this.uid = uid;
	}

	public User(Integer uid, Team team, String uname, String upassword, String isfootballer) {
		this.uid = uid;
		this.team = team;
		this.uname = uname;
		this.upassword = upassword;
		this.isfootballer = isfootballer;
	}

	/**
	 * @return the uid
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * @param uid
	 *            the uid to set
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * @return the team
	 */
	public Team getTeam() {
		return team;
	}

	/**
	 * @param team
	 *            the team to set
	 */
	public void setTeam(Team team) {
		this.team = team;
	}

	/**
	 * @return the uname
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * @param uname
	 *            the uname to set
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * @return the upassword
	 */
	public String getUpassword() {
		return upassword;
	}

	/**
	 * @param upassword
	 *            the upassword to set
	 */
	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

	/**
	 * @return the isfootballer
	 */
	public String getIsfootballer() {
		return isfootballer;
	}

	/**
	 * @param isfootballer
	 *            the isfootballer to set
	 */
	public void setIsfootballer(String isfootballer) {
		this.isfootballer = isfootballer;
	}

}
